default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: render_development

test:
  <<: *default
  database: render_test

production:
  <<: *default
  database: render_production
  username: render
  password: <%= ENV['RENDER_DATABASE_PASSWORD'] %>
